"use strict";

// tests for createCustomer
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper(
  "createCustomer",
  "../../../src/functions/createCustomer.js",
  "createCustomer"
);

describe("createCustomer", () => {
  before((done) => {
    done();
  });

  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
