"use strict";

// tests for refreshToken
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper(
  "refreshToken",
  "../../../src/functions/refreshToken.js",
  "refreshToken"
);

describe("refreshToken", () => {
  before((done) => {
    done();
  });

  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
