"use strict";

// tests for registerApp
// Generated by serverless-mocha-plugin

const mochaPlugin = require("serverless-mocha");
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper(
  "registerApp",
  "../../../src/functions/registerApp.js",
  "registerApp"
);

describe("registerApp", () => {
  before((done) => {
    done();
  });

  it("implement tests here", async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
